#!/usr/bin/python
import os
import re
import time
import argparse
from subprocess import TimeoutExpired, check_output, Popen, PIPE, STDOUT, DEVNULL
from tempfile import mkdtemp
from contextlib import contextmanager

parser = argparse.ArgumentParser(description=r'''
GPU fan control for Linux.

By default, this uses a clamped linear fan curve, going from 30% below 55C to 99%
above 80C. There's also a small hysteresis gap, because _changes_ in fan noise 
are a lot more distracting than steady fan noise. 

I can't claim it's optimal, but it Works For My Machine (TM). Full load is about 
75C and 80%.
''')
parser.add_argument('--temp', nargs='+', default=[55, 80], type=float, help='The temperature ranges where the fan speed will increase linearly')
parser.add_argument('--speed', nargs='+', default=[30, 99], type=float, help='The fan speed ranges')
parser.add_argument('--hyst', nargs='?', default=2, type=float, help='The hysteresis gap. Large gaps will reduce how often the fan speed is changed, but might mean the fan runs faster than necessary')
parser.add_argument('--kill', action='store_true', default=False, help='Whether to kill existing Xorg sessions')
parser.add_argument('--verbose', action='store_true', default=False, help='Whether to print extra debugging information')
parser.add_argument("--display", type=str, default=":0")
args = parser.parse_args()

T_HYST =  args.hyst

assert len(args.temp) == len(args.speed), 'temp and speed should have the same length'
assert len(args.temp) >= 2, 'Please use at least two points for temp'
assert len(args.speed) >= 2, 'Please use at least two points for speed'

def log_output(command, ok=(0,)):
    output = []
    if args.verbose:
        print('Command launched: ' + ' '.join(command))
    p = Popen(command, stdout=PIPE, stderr=STDOUT)
    try:
        p.wait(60)
        for line in p.stdout:
            output.append(line.decode().strip())
            if args.verbose:
                print(line.decode().strip())
        if args.verbose:
            print('Command finished')
    except TimeoutExpired:
        print('Command timed out: ' + ' '.join(command))
        raise
    finally:
        if p.returncode not in ok:
            print('\n'.join(output))
            raise ValueError('Command crashed with return code ' + str(p.returncode) + ': ' + ' '.join(command))
        return '\n'.join(output)

def decimalize(bus):
    """Converts a bus ID to an xconf-friendly format by dropping the domain and converting each hex component to 
    decimal"""
    return ':'.join([str(int('0x' + p, 16)) for p in re.split('[:.]', bus[9:])])

def gpu_buses():
    return log_output(['nvidia-smi', '--format=csv,noheader', '--query-gpu=pci.bus_id']).splitlines()

def query(bus, field):
    [line] = log_output(['nvidia-smi', '--format=csv,noheader', '--query-gpu='+field, '-i', bus]).splitlines()
    return line

def temperature(bus):
    return int(query(bus, 'temperature.gpu'))

def config():
    """Writes out the X server config for all GPUs to a temporary directory"""
    tempdir = mkdtemp(prefix='cool-gpu')

    conf = os.path.join(tempdir, 'xorg.conf')
    log_output(['nvidia-xconfig', '--enable-all-gpus', '--cool-bits=4', '--allow-empty-initial-configuration', '-o', conf])

    return conf

def xserver():
    """Starts the X server""" 
    conf = config()
    xorgargs = ['Xorg', args.display, '-once', '-config', conf]
    print('Starting xserver: '+' '.join(xorgargs))
    p = Popen(xorgargs, stdout=DEVNULL, stderr=DEVNULL)
    if args.verbose:
        print('Started xserver')
    return p

def xserver_pids():
    return list(map(int, log_output(['pgrep', 'Xorg'], ok=(0, 1)).splitlines()))

def kill_xservers():
    """If there are already X servers attach to the GPUs, they'll stop us from setting up our own. Right now we
    can't make use of existing X servers for the reasons detailed here https://github.com/andyljones/coolgpus/issues/1
    """
    servers = xserver_pids()
    if servers:
        if args.kill:
            print('Killing all running X servers, including ' + ", ".join(map(str, servers)))
            log_output(['pkill', '-9', 'Xorg'], ok=(0, 1))
            for _ in range(10):
                if xserver_pids():
                    print('Awaiting X server shutdown')
                    time.sleep(1)
                else:
                    print('All X servers killed')
                    return
            raise IOError('Failed to kill existing X servers. Try killing them yourself before running this script')
        else:
            raise IOError('There are already X servers active. Either run the script with the `--kill` switch, or kill them yourself first')
    else:
        print('No existing X servers, we\'re good to go')
        return 

@contextmanager
def xservers():
    """A context manager for launching an X server for each GPU in a list. Yields the mapping from bus ID to 
    display ID, and cleans up the X servers on exit."""
    kill_xservers()
    xserver_process = None
    try:
        xserver_process = xserver()
        yield None
    finally:
        print(f'Terminating xserver for display {args.display}.')
        xserver_process.terminate()

def determine_segment(t):
    '''Determines which piece (segment) of a user-specified piece-wise function 
    t belongs to. For example:
        args.temp = [30, 50, 70, 90]
        (segment 0) 30 (0 segment) 50 (1 segment) 70 (2 segment) 90 (segment 2)
        args.speed = [10, 30, 50, 75]
        (segment 0) 10 (0 segment) 30 (1 segment) 50 (2 segment) 75 (segment 2)'''
    # TODO: assert temps and speeds are sorted
    # the loop exits when:
    #   a) t is less than the min temp (returns: segment 0)
    #   b) t belongs to a segment (returns: the segment)
    #   c) t is higher than the max temp (return: the last segment)
    segments = zip(
            args.temp[:-1], args.temp[1:], 
            args.speed[:-1], args.speed[1:])
    for temp_a, temp_b, speed_a, speed_b in segments:
        if t < temp_a:
            break
        if temp_a <= t < temp_b:
            break
    return temp_a, temp_b, speed_a, speed_b

def min_speed(t):
    temp_a, temp_b, speed_a, speed_b = determine_segment(t)
    load = (t - temp_a)/float(temp_b - temp_a)
    return int(min(max(speed_a + (speed_b - speed_a)*load, speed_a), speed_b))

def max_speed(t):
    return min_speed(t + T_HYST)

def target_speed(s, t):
    l, u = min_speed(t), max_speed(t)
    return min(max(s, l), u), l, u

def assign(display, command):
    # Our duct-taped-together xorg.conf leads to some innocent - but voluminous - warning messages about
    # failing to authenticate. Here we dispose of them
    log_output(['nvidia-settings', '-a', command, '-c', display])

def set_speed(id, target):
    assign(args.display, f'[gpu:{id}]/GPUFanControlState=1')
    assign(args.display, f'[fan:{id}]/GPUTargetFanSpeed='+str(int(target)))
    
def get_valid_value_for_GPUTargetFanSpeed(buses):
    
    temp_range = {}
    for id, bus in enumerate(buses):
        output = log_output(['nvidia-settings', '-q', f"[fan:{id}]/GPUTargetFanSpeed", '-c', args.display])

        match = re.search(r'are\sin\sthe\srange\s+(\d+)\s+-\s+(\d+)', output, re.DOTALL)
        if match:
            min_value = int(match.group(1))
            max_value = int(match.group(2))
            
            temp_range[bus] = (min_value, max_value)
        else:
            raise Exception("Cloudn't get valid value for GPUTargetFanSpeed.")
    return temp_range

def clamp(v, m, M):
    return min(M, max(m, v))

def manage_fans(buses):
    """Launches an X server for each GPU, then continually loops over the GPU fans to set their speeds according
    to the GPU temperature. When interrupted, it releases the fan control back to the driver and shuts down the
    X servers"""
    try:
        speeds = [0 for _ in buses]
        
        temp_range = get_valid_value_for_GPUTargetFanSpeed(buses)
        while True:
            start_time = time.time()
            for id, bus in enumerate(buses):
                temp = temperature(bus)
                s, l, u = target_speed(speeds[id], temp)
                s = clamp(s, temp_range[bus][0], temp_range[bus][1])
                l = clamp(l, temp_range[bus][0], temp_range[bus][1])
                u = clamp(u, temp_range[bus][0], temp_range[bus][1])
                if s != speeds[id]:
                    print('GPU {}, {}C -> [{}%-{}%]. Setting speed to {}%'.format(id, temp, l, u, s))
                    set_speed(id, s)
                else:
                    print('GPU {}, {}C -> [{}%-{}%]. Leaving speed at {}%'.format(id, temp, l, u, s))

            elapsed_time = time.time() - start_time
            if elapsed_time < 7:
                time.sleep(7 - elapsed_time)
    finally:
        for id, bus in enumerate(buses):
            assign(args.display, f'[gpu:{id}]/GPUFanControlState=0')
            print('Released fan speed control for GPU '+ str(id))

def run():
    buses = gpu_buses() 
    with xservers():
        manage_fans(buses)

if __name__ == '__main__':
    run()
